{{- $secret := lookup "v1" "Secret" .Release.Namespace "existing-secret" }}

{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: existing-secret
type: Opaque
stringData:
  password: generated-by-helm-v2
{{- end }}
