{{- $existing := lookup "v1" "Secret" .Release.Namespace "existing-secret" }}

apiVersion: v1
kind: Secret
metadata:
  name: existing-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ if $existing }}
    {{ index $existing.data "password" | b64dec }}
  {{ else }}
    generated-by-helm
  {{ end }}
